"use client";
import { useEffect, useMemo, useState } from "react";
import { API_BASE, apiGet, ExperimentSummary, parseJson, Trial } from "@/lib/api";

interface WorldData {
  experiment_id: string;
  trial_id: string;
  seed: number;
  config: Record<string, number | string>;
  grid: number[][];
  trajectory: { agent: number[]; action: number; reward: number; collected: number; energy: number }[];
  total_reward: number;
  steps: number;
  terminated: boolean;
  morphology: Record<string, unknown>;
}

const COLORS: Record<number, string> = {
  0: "#121821",
  1: "#3b4657",
  2: "#3fb950",
  3: "#f85149",
  4: "#4f9cf9",
};

export default function WorldPage() {
  const [exps, setExps] = useState<ExperimentSummary[]>([]);
  const [expId, setExpId] = useState("");
  const [trials, setTrials] = useState<Trial[]>([]);
  const [trialId, setTrialId] = useState("");
  const [seed, setSeed] = useState(101);
  const [world, setWorld] = useState<WorldData | null>(null);
  const [step, setStep] = useState(0);
  const [err, setErr] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    apiGet<ExperimentSummary[]>("/api/experiments")
      .then((d) => {
        setExps(d);
        if (d.length) setExpId(d[0].id);
      })
      .catch((e) => setErr(String(e)));
  }, []);

  useEffect(() => {
    if (!expId) return;
    apiGet<{ trials: Trial[] }>(`/api/experiments/${expId}`)
      .then((d) => {
        const trained = d.trials.filter(
          (t) => t.status === "done" && !["random", "heuristic"].includes(t.algorithm)
        );
        setTrials(trained);
        setTrialId(trained[0]?.id ?? "");
      })
      .catch((e) => setErr(String(e)));
  }, [expId]);

  useEffect(() => {
    if (!expId || !trialId) return;
    setLoading(true);
    setWorld(null);
    setErr(null);
    apiGet<WorldData>(`/api/world?experiment=${expId}&trial=${trialId}&seed=${seed}`)
      .then((w) => {
        setWorld(w);
        setStep(0);
      })
      .catch((e) => setErr(String(e)))
      .finally(() => setLoading(false));
  }, [expId, trialId, seed]);

  const grid = useMemo(() => {
    if (!world) return null;
    const g = world.grid.map((row) => row.slice());
    if (world.trajectory.length > 0) {
      const pos = step === 0 ? null : world.trajectory[step - 1].agent;
      if (pos) g[pos[0]][pos[1]] = 4;
    }
    return g;
  }, [world, step]);

  return (
    <div>
      <h1>World viewer</h1>
      <p className="sub">
        Deterministic environment inspection with a trained organism replayed from stored
        state. The grid, agent and trajectory are regenerated by the backend — not mocked.
      </p>

      <div className="panel">
        <div className="row">
          <label>experiment</label>
          <select value={expId} onChange={(e) => setExpId(e.target.value)}>
            {exps.map((e) => (
              <option key={e.id} value={e.id}>
                {e.name} ({e.id})
              </option>
            ))}
          </select>
          <label>trial</label>
          <select value={trialId} onChange={(e) => setTrialId(e.target.value)}>
            {trials.map((t) => (
              <option key={t.id} value={t.id}>
                {t.algorithm} · seed {t.seed}
              </option>
            ))}
          </select>
          <label>world seed</label>
          <input
            type="number"
            value={seed}
            onChange={(e) => setSeed(Number(e.target.value))}
            style={{ width: 90 }}
          />
        </div>
      </div>

      {loading && <p className="muted">replaying…</p>}
      {err && (
        <div className="panel">
          <p className="err">{err}</p>
          <p className="muted">
            Baselines (random/heuristic) have no stored organism; pick a trained trial.
            API: {API_BASE}
          </p>
        </div>
      )}

      {grid && world && (
        <div className="panel">
          <div className="row" style={{ justifyContent: "space-between" }}>
            <div>
              <strong>step {step}</strong> / {world.trajectory.length} · total reward{" "}
              {world.total_reward.toFixed(2)} · {world.terminated ? "terminated" : "ended"}
            </div>
            <div className="row">
              <button onClick={() => setStep((s) => Math.max(0, s - 1))}>◀</button>
              <input
                type="range"
                min={0}
                max={world.trajectory.length}
                value={step}
                onChange={(e) => setStep(Number(e.target.value))}
              />
              <button onClick={() => setStep((s) => Math.min(world.trajectory.length, s + 1))}>▶</button>
            </div>
          </div>
          <div className="grid" style={{ gridTemplateColumns: `repeat(${world.grid[0].length}, 16px)`, marginTop: 12 }}>
            {grid.map((row, r) =>
              row.map((cell, c) => (
                <div key={`${r}-${c}`} className="cell" style={{ background: COLORS[cell] }} title={`${r},${c}`} />
              ))
            )}
          </div>
          <div className="legend">
            <span><span className="swatch" style={{ background: COLORS[0], border: "1px solid #333" }} />empty</span>
            <span><span className="swatch" style={{ background: COLORS[1] }} />obstacle</span>
            <span><span className="swatch" style={{ background: COLORS[2] }} />resource</span>
            <span><span className="swatch" style={{ background: COLORS[3] }} />hazard</span>
            <span><span className="swatch" style={{ background: COLORS[4] }} />agent</span>
          </div>
          <p className="muted" style={{ marginTop: 10 }}>
            morphology: {JSON.stringify(world.morphology)} · obs mode {String(world.config.obs_mode)}
          </p>
        </div>
      )}
    </div>
  );
}
